* File: NAND.pex.netlist.NAND.pxi
* Created: Mon May  8 18:33:37 2023
* 
x_PM_NAND%A N_A_MnMos1_g N_A_MpMos1_g A PM_NAND%A
x_PM_NAND%N1_S N_N1_S_MnMos2_d N_N1_S_MnMos1_s PM_NAND%N1_S
x_PM_NAND%OUT_2 N_OUT_2_MpMos2_d N_OUT_2_MpMos1_d N_OUT_2_MnMos1_d OUT_2
+ PM_NAND%OUT_2
x_PM_NAND%B N_B_MnMos2_g N_B_MpMos2_g B PM_NAND%B
x_PM_NAND%VDD N_VDD_MpMos1_b N_VDD_MpMos1_s N_VDD_MpMos2_s VDD PM_NAND%VDD
x_PM_NAND%GND N_GND_MnMos1_b N_GND_MnMos2_s GND PM_NAND%GND
